# Always validate the PR title, and ignore the commits.
titleOnly: true

types:
  - feat     # new feature for the user, not a new feature for build script.
  - fix      # bug fix for the user, not a fix to a build script.
  - docs     # changes to the documentation.
  - style    # formatting, missing semi colons, etc; no production code change.
  - refactor # refactoring production code, eg. renaming a variable.
  - test     # adding missing tests, refactoring tests; no production code change.
  - chore    # updating grunt tasks etc; no production code change.
  - perf     # performance improvement.
  - ci       # related to continuous integration, like GitHub workflows.
  - revert   # a revert of a previous change.

# Disallow use of Merge commits (eg on github: "Merge branch 'master' into feature/ride-unicorns").
allowMergeCommits: false

# Disallow use of Revert commits (eg on github: "Revert "feat: ride unicorns"").
allowRevertCommits: false

# scopes:
#  - not_implemented_yet
