-ifdef(OTP_RELEASE).
    -define(IS_DOC_ATTRS_SUPPORTED, ?OTP_RELEASE >= 27).
-else.
    -define(IS_DOC_ATTRS_SUPPORTED, false).
-endif.

-ifdef(OTP_RELEASE).
    -define(IS_ERROR_INFO_SUPPORTED, ?OTP_RELEASE >= 24).
-else.
    -define(IS_ERROR_INFO_SUPPORTED, false).
-endif.
