name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    name: OTP ${{ matrix.otp_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [24, 25, 26, 27]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: rebar3 compile
      - name: Run tests
        run: rebar3 do ct, eunit
      - name: Run dialyzer
        run: rebar3 dialyzer
