name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux:
    name: OTP ${{ matrix.otp_version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: [24, 25, 26, 27]
        os: [ubuntu-latest]

    container:
      image: erlang:${{ matrix.otp_version }}

    steps:
      - uses: actions/checkout@v2

      - name: Compile
        env:
          ERL_FLAGS: "-enable-feature maybe_expr"
        run: rebar3 compile

      - name: Run CT tests
        env:
          ERL_FLAGS: "-enable-feature maybe_expr"
        run: rebar3 ct

      - name: Run EUnit tests
        env:
          ERL_FLAGS: "-enable-feature maybe_expr"
        run: rebar3 eunit

      - name: Run dialyzer
        env:
          ERL_FLAGS: "-enable-feature maybe_expr"
        run: rebar3 dialyzer
